### ISSUE TITLE
Implement autocomplete

### ISSUE THREAD

**Issue by ale152** [EdmundOgban/Limnoria#1]
It'd be super cool if there was a function like \autocomplete _text_ that returns the first result of google search autocomplete when you type _text_ in the search bar \o/

**Comment by EdmundOgban** [comment]
Are you aware of any public API or something that can be leveraged to implement it?

**Comment by ale152** [comment]
This one seems pretty straightforward to implement:
https://stackoverflow.com/questions/6428502/google-search-autocomplete-api

**Comment by EdmundOgban** [comment]
https://suggestqueries.google.com/complete/search?client=firefox&q=<query> seems to work well. Thank you, I'll get on it soon.

**Comment by EdmundOgban** [comment]
Done in commit 2a618725788d105d5ecfd9a512c4a04a4aa44783
